#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wclean ./src/combustionModels
wclean ./applications/solver/ndtblIntegrationFoam

# ----------------------------------------------------------------- end-of-file
