#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake ./src/combustionModels
wmake ./applications/solver/ndtblIntegrationFoam


# ----------------------------------------------------------------- end-of-file
