#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Delete time folders
foamListTimes -rm
rm -rf 0

# Delete log files
rm -rf ./log*

# Delete mesh
rm -rf ./constant/polyMesh

# Delete tables
rm -f ./constant/Tables.ndtbl
