#!/bin/bash
# Load OpenFOAM run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# User settings
TABLERESOLUTION="51"                # select table resolution (2, 21, 31, 41, 46, 51)
PARALLEL=true                       # parallel mode?

# Link tables
ln -sf ../tables/tables_"$TABLERESOLUTION"/Table1_table ./constant
ln -sf ../tables/tables_"$TABLERESOLUTION"/Table2_table ./constant
ln -sf ../tables/tables_"$TABLERESOLUTION"/Table3_table ./constant
ln -sf ../tables/tables_"$TABLERESOLUTION"/Table4_table ./constant

# Copy initial conditions
cp -rf 0_orig 0

# Create Mesh
runApplication blockMesh

if $PARALLEL; then
    # Decompose case
    runApplication decomposePar

    # Run solver in parallel
    runApplication mpirun -np 4 bwRSE4HPCFoam -parallel

    # Reconstruct results
    runApplication reconstructPar

    # Remove processor directories
    rm -rf processor*
else
    # Serial run
    runApplication bwRSE4HPCFoam
fi
