name: CI

on:
  # Run on pushes to the main branch
  push:
    branches:
      - main
  # Run on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # Run upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Set up OpenFOAM
        uses: gerlero/setup-openfoam@v1
        with:
          openfoam-version: 10

      - name: Build project
        shell: bash
        run: |
          ./Allwmake

      - name: Clean up project
        shell: bash
        run: |
          ./Allclean
